name: test-deno-executable-non-compiled
on:
  pull_request:
    branches: [main]
jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
    steps:
      - name: Test Deno Executable
        uses: flowscripter/.github/actions/test-deno-executable-non-compiled@v1
